config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :posts do
    member do
      post 'like'
      delete 'unlike'
    end
    resources :comments, only: [:create]
  end
  resources :users, only: [:index] do
    member do
      get 'profile', to: 'profiles#show'
    end
  end
  resources :follow_requests, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @post, notice: 'Comment was successfully created.'
    else
      redirect_to @post, alert: 'Comment could not be created.'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/models/content.rb
# app/models/content.rb
class Content < ApplicationRecord
  belongs_to :contentable, polymorphic: true
  has_one_attached :image
end

app/models/follow_request.rb
class FollowRequest < ApplicationRecord
    belongs_to :follower, class_name: 'User'
    belongs_to :followed, class_name: 'User'
  end
  

app/models/like.rb
# app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
# app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :content, as: :contentable, dependent: :destroy

  accepts_nested_attributes_for :content
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :follow_requests_as_follower, foreign_key: :follower_id, class_name: 'FollowRequest'
  has_many :follow_requests_as_followed, foreign_key: :followed_id, class_name: 'FollowRequest'

  has_one_attached :profile_picture

  after_create :send_welcome_email

  def profile_picture_url
    if profile_picture.attached?
      Rails.application.routes.url_helpers.rails_blob_url(profile_picture, only_path: true)
    else
      gravatar_url
    end
  end

  private

  def gravatar_url
    "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email.downcase)}"
  end

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_later
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/home_controller.rb
# app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    following_ids = current_user.follow_requests_as_follower.where(status: 'accepted').pluck(:followed_id)
    @posts = Post.where(user_id: [current_user.id, *following_ids]).order(created_at: :desc)
  end
end

app/controllers/posts_controller.rb
# app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :unlike]
  
    def index
      following_ids = current_user.follow_requests_as_follower.where(status: 'accepted').pluck(:followed_id)
      @posts = Post.where(user_id: [current_user.id, *following_ids]).order(created_at: :desc)
    end
  
    def show
    end
  
    def new
      @post = Post.new
      @post.build_content
    end
  
    def create
      @post = current_user.posts.build(post_params)
      if @post.save
        redirect_to @post, notice: 'Post was successfully created.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @post.update(post_params)
        redirect_to @post, notice: 'Post was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end
  
    def like
      @post.likes.create(user: current_user)
      redirect_to @post
    end
  
    def unlike
      @post.likes.find_by(user: current_user)&.destroy
      redirect_to @post
    end
  
    private
  
    def set_post
      @post = Post.find(params[:id])
    end
  
    def post_params
      params.require(:post).permit(:content_attributes => [:body, :image])
    end
  end
  

app/controllers/profiles_controller.rb
# app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
      @users = User.all
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->
<div class="parallax-container">
  <div class="parallax-content">
    <h1>Welcome to Face Of The Book</h1>
    <%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
  </div>
</div>

<div class="content-container">
  <h2>Recent Posts</h2>
  <% @posts.each do |post| %>
    <div class="post">
      <h3><%= post.user.email %></h3>
      <% if post.content.image.attached? %>
        <%= image_tag post.content.image, class: 'post-image' %>
      <% end %>
      <p><%= post.content.body %></p>
      <p>Likes: <%= post.likes.count %></p>
      <% if post.likes.find_by(user: current_user) %>
        <%= button_to 'Unlike', unlike_post_path(post), method: :delete, class: 'btn btn-secondary' %>
      <% else %>
        <%= button_to 'Like', like_post_path(post), class: 'btn btn-primary' %>
      <% end %>

      <h4>Comments</h4>
      <ul>
        <% post.comments.each do |comment| %>
          <li>
            <p><%= comment.content %></p>
            <p>Author: <%= comment.user.email %></p>
          </li>
        <% end %>
      </ul>

      <%= form_with(model: [ post, post.comments.build ], local: true) do |form| %>
        <div class="form-group">
          <%= form.label :content, "Add a comment" %>
          <%= form.text_area :content, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= form.submit 'Comment', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb -->
<!DOCTYPE html>
<html>
  <head>
    <title>Face Of The Book</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header></header>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<!-- app/views/posts/index.html.erb -->
<h1>Posts</h1>
<%= link_to 'New Post', new_post_path %>
<ul>
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.content, post %>
      <p>Author: <%= post.user.email %></p>
      <p>Likes: <%= post.likes.count %></p>
      <ul>
        <% post.comments.each do |comment| %>
          <li>
            <p><%= comment.content %></p>
            <p>Author: <%= comment.user.email %></p>
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<!-- app/views/posts/new.html.erb -->
<h1>New Post</h1>
<%= form_with(model: @post, local: true) do |form| %>
  <div>
    <%= form.fields_for :content do |content_form| %>
      <div>
        <%= content_form.label :body, "Text Post" %>
        <%= content_form.text_area :body %>
      </div>
      <div>
        <%= content_form.label :image, "Photo Post" %>
        <%= content_form.file_field :image %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

<!-- app/views/posts/edit.html.erb -->
<h1>Edit Post</h1>
<%= form_with(model: @post, local: true) do |form| %>
  <div>
    <%= form.fields_for :content do |content_form| %>
      <div>
        <%= content_form.label :body, "Text Post" %>
        <%= content_form.text_area :body %>
      </div>
      <div>
        <%= content_form.label :image, "Photo Post" %>
        <%= content_form.file_field :image %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/show.html.erb
<!-- app/views/posts/show.html.erb -->
<h1><%= @post.content.body %></h1>
<% if @post.content.image.attached? %>
  <%= image_tag @post.content.image %>
<% end %>
<p>Author: <%= @post.user.email %></p>
<p>Likes: <%= @post.likes.count %></p>
<% if @post.likes.find_by(user: current_user) %>
  <%= button_to 'Unlike', unlike_post_path(@post), method: :delete %>
<% else %>
  <%= button_to 'Like', like_post_path(@post) %>
<% end %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<h2>Comments</h2>
<ul>
  <% @post.comments.each do |comment| %>
    <li>
      <p><%= comment.content %></p>
      <p>Author: <%= comment.user.email %></p>
    </li>
  <% end %>
</ul>

<h2>New Comment</h2>
<%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>
  <div>
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/show.html.erb
<!-- app/views/profiles/show.html.erb -->
<h1><%= @user.email %>'s Profile</h1>
<%= image_tag @user.profile_picture_url, alt: "Profile Picture" %>
<h2>Posts</h2>
<ul>
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.content, post %>
      <p>Author: <%= post.user.email %></p>
      <p>Likes: <%= post.likes.count %></p>
      <ul>
        <% post.comments.each do |comment| %>
          <li>
            <p><%= comment.content %></p>
            <p>Author: <%= comment.user.email %></p>
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

app/views/users/index.html.erb
<!-- app/views/users/index.html.erb -->
<h1>All Users</h1>
<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.email, profile_user_path(user) %>
      <% if current_user.follow_requests_as_follower.where(followed: user, status: 'pending').exists? %>
        <button disabled>Follow Request Sent</button>
      <% elsif current_user.follow_requests_as_follower.where(followed: user, status: 'accepted').exists? %>
        <button disabled>Following</button>
      <% else %>
        <%= button_to 'Follow', follow_requests_path(follow_request: { followed_id: user.id }), method: :post %>
      <% end %>
    </li>
  <% end %>
</ul>